apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - flyway-job.yaml
secretGenerator:
- name: flyway-config
  files:
  - conf/flyway.conf
generatorOptions:
 disableNameSuffixHash: true